### ISSUE TITLE
Era Sepolia Testnet latest dump link is broken

### ISSUE THREAD

**Issue by achiko** [matter-labs/ansible-en-role#20]
**Era Sepolia Testnet latest dump**  the link is broken : (https://storage.googleapis.com/zksync-era-boojnet-external-node-snapshots/external_node_latest.pgdump)

<img width="918" alt="image" src="https://github.com/matter-labs/ansible-en-role/assets/3051858/a7da88aa-b8f8-4786-ac6f-caeca907db39">

**Comment by hatemosphere** [comment]
fixed in https://github.com/matter-labs/ansible-en-role/pull/23
