### ISSUE TITLE
external_node-1  | error: unexpected argument '--enable-snapshots-recovery' found

### ISSUE THREAD

**Issue by lion100x** [matter-labs/ansible-en-role#29]
#### 📝 Description

Using the ansible-en role release v3.8.1, after complete configuration with ansible role 
playbook has enable_snapshots_recovery: true and enable_consensus: false

Proceed to run docker compose up -d in /opt/en
Getting error 

external_node-1  | Usage: zksync_external_node <--enable-consensus|--components <COMPONENTS>|--config-path <CONFIG_PATH>|--secrets-path <SECRETS_PATH>|--external-node-config-path <EXTERNAL_NODE_CONFIG_PATH>|--consensus-path <CONSENSUS_PATH>>
external_node-1  |
external_node-1  | For more information, try '--help'.
external_node-1  | error: unexpected argument '--enable-snapshots-recovery' found
external_node-1  |
external_node-1  |   tip: a similar argument exists: '--enable-consensus'
external_node-1  |
external_node-1  | Usage: zksync_external_node <--enable-consensus|--components <COMPONENTS>|--config-path <CONFIG_PATH>|--secrets-path <SECRETS_PATH>|--external-node-config-path <EXTERNAL_NODE_CONFIG_PATH>|--consensus-path <CONSENSUS_PATH>>

#### 🔄 Reproduction Steps

docker compose up -d 
in /opt/en

#### 🤔 Expected Behavior

--enable-snapshots-recovery should not be an unexpected argument.

#### 😯 Current Behavior

As in description

#### 🖥️ Environment

Any relevant environment details like:

* Ansible version ansible [core 2.17.3]
* Operating system Ubuntu Jammy 22.04
* External Node version 24.23.0 or 24.6.0

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output
docker compose logs related error pasted in description.
```
Paste any relevant log output here.
```

**Comment by hatemosphere** [comment]
@lion100x thanks for reporting, this is now fixed in https://github.com/matter-labs/ansible-en-role/releases/tag/v3.9.0
